wrote backend and created databasse
vigge93/PA1450-Development-task pull request #44
Opened 2020-05-13 15:22 UTC by KishFalk

Co-authored-by: karloscarsvensson <karloscarsvensson@gmail.com>
Co-authored-by: ubk8751 <ubk8751@gmail.com>

2020-05-13 15:22 UTC, pep8speaks commented
Hello @KishFalk! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`program/backend.py`](https://github.com/vigge93/PA1450-Development-task/blob/6c87b4efbe203d8db5f37cb9698259b3bad084da/program/backend.py):

> [Line 20:80](https://github.com/vigge93/PA1450-Development-task/blob/6c87b4efbe203d8db5f37cb9698259b3bad084da/program/backend.py#L20): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (89 > 79 characters)
> [Line 27:80](https://github.com/vigge93/PA1450-Development-task/blob/6c87b4efbe203d8db5f37cb9698259b3bad084da/program/backend.py#L27): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (81 > 79 characters)
> [Line 51:80](https://github.com/vigge93/PA1450-Development-task/blob/6c87b4efbe203d8db5f37cb9698259b3bad084da/program/backend.py#L51): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (115 > 79 characters)

2020-05-13 17:48 UTC, vigge93 requested changes
* Databasen ligger på fel ställe, ta bort denna och lägg den på rätt ställe (instance mappen enl. specifikation)
* Det finns inga tester, vet alltså inte om koden fungerar, kan tipsa om tempfile: "Untested code is broken code" - Maurits van Rees

2020-05-13 17:48 UTC, vigge93 commented on .vscode/settings.json
> -    "python.pythonPath": "venv\\Scripts\\python.exe",
Ändra tillbaka detta

2020-05-13 17:48 UTC, vigge93 commented on program/backend.py
> +run()
Bättre att anropa run via commandotolken enligt https://flask.palletsprojects.com/en/1.1.x/tutorial/database/#id3, då jag antar att denna initialiserar databasen, vilket i nuläget kommer göras varje gång filen importeras.

2020-05-13 19:28 UTC, vigge93 commented on program/backend.py
> +    globals()[sys.argv[1]]()
Intressant lösning

2020-05-14 06:50 UTC, vigge93 requested changes
AttributeID kolumnen blir NULL i Datapoints tabellen

2020-05-14 13:17 UTC, pep8speaks commented
Hello @KishFalk! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`program/tests/test_backend.py`](https://github.com/vigge93/PA1450-Development-task/blob/092ce82b3765c67a322b14d2cec3ae0ed60d80ce/program/tests/test_backend.py):

> [Line 1:80](https://github.com/vigge93/PA1450-Development-task/blob/092ce82b3765c67a322b14d2cec3ae0ed60d80ce/program/tests/test_backend.py#L1): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (108 > 79 characters)

2020-05-14 15:02 UTC, KishFalk commented on .vscode/settings.json
> -    "python.pythonPath": "venv\\Scripts\\python.exe",
> * Databasen ligger på fel ställe, ta bort denna och lägg den på rätt ställe (instance mappen enl. specifikation)
> * Det finns inga tester, vet alltså inte om koden fungerar, kan tipsa om tempfile: "Untested code is broken code" - Maurits van Rees

Databasen ligger på rätt ställe nu, tester är tillagda.

2020-05-14 15:03 UTC, KishFalk commented on program/backend.py
> +run()
Detta är fixat

2020-05-14 15:03 UTC, KishFalk commented
> AttributeID kolumnen blir NULL i Datapoints tabellen

Fixat detta med

2020-05-18 19:33 UTC, vigge93 requested changes

2020-05-18 19:33 UTC, vigge93 commented on specifications/frontend/Frontend-codespecs.md
> -   "timeIntervallType": "year/months/intervall",
Kommunikationen mellan hemsidan och webservern använder "year/month/date" samt "attribute", medan kommunikationen mellan webservern och backend använder "MONTH/TIME_INTERVALL" samt "Argument"

2020-05-20 13:26 UTC, vigge93 requested changes

2020-05-20 13:26 UTC, vigge93 commented on program/backend.py
> +        sql_insert = """ INSERT INTO """+table+"""
Se tidigare kommentarer på sql queries

2020-05-20 13:26 UTC, vigge93 commented on program/backend.py
> +        for i in data[row][0]:
Snälla ta en titt på datetime
https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat
alternativt
https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime

2020-05-20 13:26 UTC, vigge93 commented on program/backend.py
> +    for i in data[parameter_index_row + 1][parameter_index_column]:
Detta klarar bara åäö, kolla på unidecode för att utöka till alla(nästan) unicode tecken
https://pypi.org/project/Unidecode/

2020-05-20 13:26 UTC, vigge93 commented on program/backend.py
> +    sql_insert = """ INSERT INTO """+table+"""(Name, DisplayName, Unit)
Se tidigare kommentarer om sql

2020-05-20 13:26 UTC, vigge93 commented on program/backend.py
> +    sql_insert += ('"' + string_to_add + '"' + ',')
Se tidigare kommentarer om sql

2020-05-20 13:26 UTC, vigge93 commented on program/backend.py
> +
Extra rad

2020-05-20 13:26 UTC, vigge93 commented on program/backend.py
> +    globals()[sys.argv[1]](dic)
dic?

2020-05-20 13:26 UTC, vigge93 commented on program/tests/test_backend.py
> +# b = tempfile.NamedTemporaryFile(prefix="test", suffix=".img")
Utkommenterad kod

2020-05-20 13:26 UTC, vigge93 commented on program/tests/test_backend.py
> +#  assert res2 == "File is not in the correct format"
Utkommenterad kod

2020-05-20 13:26 UTC, vigge93 commented on program/tests/test_backend.py
> +#  res2 = ext_check(b)
Utkommenterad kod

2020-05-20 13:31 UTC, ubk8751 commented on program/backend.py
> +dic = {"timeArgument": ["01"],
Oh, det är för när vi testade att koden funkade när vi körde den. Borde vi ta bort den?

2020-05-20 13:34 UTC, ubk8751 commented on program/backend.py
> +        start_date[1] = int(start_date[1])
Nej, vi gör det för att få det i samma format som i databasen. Det görs automatiskt om till "1" när det läggs till i databasen, så vi måste göra så att all input inte har den nollan när vi läser av den.

2020-05-20 13:35 UTC, ubk8751 commented on program/backend.py
> +        print(data_to_return)
Debugging?

2020-05-20 13:35 UTC, ubk8751 commented on program/backend.py
> +        month = int(month)
se ovanstående svar

2020-05-20 14:58 UTC, KishFalk commented on program/backend.py
> +    close_db(db)
process_file(file) funktionen ska enligt API specifications kallas från frontend

2020-05-20 15:06 UTC, KishFalk commented on program/backend.py
> +dic = {"timeArgument": ["01"],
Fixat

2020-05-20 15:06 UTC, KishFalk commented on program/backend.py
> +    data_to_return = {}
Fixat

2020-05-20 15:07 UTC, KishFalk commented on program/backend.py
> +        data_to_return["Name"] = row[0]
Fixat

2020-05-20 15:08 UTC, KishFalk commented on program/backend.py
> +        data_to_return["DisplayName"] = row[1]
Fixat

2020-05-20 15:08 UTC, vigge93 commented on program/backend.py
> +    close_db(db)
Alla vägar genom funktionen returnerar innan rad 34

2020-05-20 15:08 UTC, KishFalk commented on program/backend.py
> +    """Get data from using filters from databases."""
Skrivit om meningen

2020-05-20 15:14 UTC, KishFalk commented on program/backend.py
> +        filters["Argument"]+"""';"""
Fixat

2020-05-20 15:15 UTC, KishFalk commented on program/backend.py
> +    data = c.execute(sql_get_id)
Vi vill hämta specifika rader, därav executen för att få dessa.

2020-05-20 15:20 UTC, KishFalk commented on program/backend.py
> +            data_to_return.append({"id": attr_id,
Fixat

2020-05-20 15:31 UTC, KishFalk commented on program/backend.py
> +                                   "year": start_date[0],
Fixat

2020-05-20 15:32 UTC, KishFalk commented on program/backend.py
> +        print(data_to_return)
Fixat

2020-05-20 15:33 UTC, KishFalk commented on program/backend.py
> +            data_to_return.append({"id": attr_id,
Fixat

2020-05-20 15:33 UTC, KishFalk commented on program/backend.py
> +        print(data_to_return)
Fixat

2020-05-20 15:38 UTC, KishFalk commented on program/backend.py
> +def ext_check(file):
Fixat

2020-05-20 16:05 UTC, KishFalk commented on program/backend.py
> +
Fixat

2020-05-20 16:05 UTC, KishFalk commented on program/backend.py
> +    globals()[sys.argv[1]](dic)
Fixat

2020-05-20 16:20 UTC, vigge93 commented on program/backend.py
> +    data = c.execute(sql_get_id)
fetchone() eller fetchall() används efter execute. Ni behöver inte använda dem, men jag tänkte att det kan underlätta vissa saker

2020-05-21 08:01 UTC, KishFalk commented on program/backend.py
> +    close_db(db)
fixat

2020-05-21 08:04 UTC, ubk8751 commented on program/tests/test_backend.py
> +# b = tempfile.NamedTemporaryFile(prefix="test", suffix=".img")
Fixat

2020-05-21 08:04 UTC, ubk8751 commented on program/tests/test_backend.py
> +#  res2 = ext_check(b)
Fixat

2020-05-21 08:04 UTC, ubk8751 commented on program/tests/test_backend.py
> +#  assert res2 == "File is not in the correct format"
Fixat

2020-05-21 10:44 UTC, ubk8751 commented on program/backend.py
> +    sql_get_id = """SELECT ID, Unit FROM Attributes WHERE Name = '""" + \
Fixat

2020-05-21 10:44 UTC, ubk8751 commented on program/backend.py
> +        sql_get_data = """SELECT * FROM Datapoints WHERE Year BETWEEN '"""+str(start_date[0])+"""'AND '"""+str(end_date[0])+"""' AND Month BETWEEN '"""+str(
Fixat

2020-05-21 10:44 UTC, ubk8751 commented on program/backend.py
> +        sql_get_data = """SELECT * FROM Datapoints WHERE Month = '""" + \
Fixat

2020-05-21 10:44 UTC, ubk8751 commented on program/backend.py
> +        sql_insert = """ INSERT INTO """+table+"""
Fixat

2020-05-21 10:44 UTC, ubk8751 commented on program/backend.py
> +        for i in data[row][0]:
Check

2020-05-21 10:45 UTC, ubk8751 commented on program/backend.py
> +    sql_insert = """ INSERT INTO """+table+"""(Name, DisplayName, Unit)
Check

2020-05-21 10:45 UTC, ubk8751 commented on program/backend.py
> +    for i in data[parameter_index_row + 1][parameter_index_column]:
Fixat

2020-05-21 10:45 UTC, ubk8751 commented on program/backend.py
> +    sql_insert += ('"' + string_to_add + '"' + ',')
Check

2020-05-21 10:46 UTC, ubk8751 submitted a review, later dismissed

2020-05-21 16:28 UTC, vigge93 requested changes

2020-05-21 16:28 UTC, vigge93 commented on program/backend.py
> +        raise Exception
Här gömmer ni det ursprungliga felmeddelandet under ett mer generellt felmeddelande vilket ger mindre info till utvecklaren. Ta hellre bort try/except helt och hållet om ni inte tänker hantera felet

2020-05-22 11:30 UTC, vigge93 approved these changes

2020-05-22 11:32 UTC, ubk8751 approved these changes

2020-05-22 12:05 UTC, DahVoid approved these changes
lit meme

2020-05-22 12:08 UTC, merged